### ISSUE TITLE
Build_snapshot, replace the computation of latest green by HEAD

### ISSUE THREAD

**Issue by erichirlemann** [SonarSource/travis-utils#2]
The sonar-green project has been set up for the build of plugins, the plugin calls `build_snapshot` to build sonarqube.zip files for further testing.
This has been set up at a time the sonarqube master branch could not be trusted. Any red master of sonarqube spread over all the plugins.
The introduction of feature branches with IT testing running on them, make the master altmost as green as it supposed to be. Basically, if the master is not green, it is an anomaly.

Change `build_snapshot` to compute SHA1 from HEAD.

Before moved to this issue, this was recorded at [SONAR-6975](https://jira.sonarsource.com/browse/SONAR-6975)

**Comment by simonbrandhof** [comment]
Examples:
`build_snapshot "SonarSource/sonarqube"`
`build "SonarSource/sonarqube" "HEAD"`
`build "SonarSource/sonarqube" "5.2"`
