### ISSUE TITLE
build_snapshot not working when pom has dependency

### ISSUE THREAD

**Issue by erichirlemann** [SonarSource/travis-utils#4]
Issue encountered on sonar-eclipse.

Project A calls `build_snapshot` project B having B noted in the POM as a dependency on SNAPSHOT version.
This causes the built to fail abruptly, without an error message.

Root cause:
When maven_local_repository executes `mvn help:evaluate` it tries to solve the pom.xml has no solution.

Solution is to change directory preventing the use of the caller pom.

**Comment by dbolkensteyn** [comment]
FYI @erichirlemann issues can be linked to PR and commits on GitHub

**Comment by tomverin** [comment]
won't fix, we do not build snapshot anymore
